### PR TITLE
Fix UI bugs

### PR DESCRIPTION
**Pull request by andriyParashchuk**
- Test and fix bugs on screens: 1366x768, 1024x768, 768x1024, 360x640
image
- Test on Windows OS image
- For browser testing use: http://ghostinspector.com/
image
- Test on IE 11
image
- Test on Chrome 65
image
- Need to align Social, Email and Telephone sections:
image
- Main screen bug, need to add more space for arrow:  arrow_bug
- After page reloading in Use cases section it doesn't show anything meaningful:
https://www.useloom.com/share/bebb02822e604175b412c3e534a38895

### CODE REVIEW

**Comment by andriyParashchuk** [comment]
Fixed all bugs except svg figure on IE browsers
staging -http://jt-pr285.surge.sh/

**Comment by andriyParashchuk** [comment]
staging -http://jt-pr285.surge.sh/
@pftg @obliviusm @sweatC  Pls check

**Review by pftg — APPROVED** [review]
LGTM

**Comment by pftg** [comment]
@sweatC @ivoJT please test all those bugs. code looks good for now.

**Comment by pftg** [comment]
@obliviusm please help with testing

**Comment by obliviusm** [comment]
ok

**Comment by obliviusm** [comment]
LGTM
@andriyParashchuk  merge with latest master and we are good

**Comment by andriyParashchuk** [comment]
@obliviusm Fixed

**Comment by sweatC** [comment]
@andriyParashchuk when you tap on `Get in touch` button, sometimes you can get this:
screenshot_2018-05-04-15-25-14

**Comment by andriyParashchuk** [comment]
@sweatC Pls make video for details bug

**Review by sweatC — APPROVED** [review]

**Pull request merged**
