### PR TITLE
Updated team members

### PR DESCRIPTION
**Pull request by freevova**

### CODE REVIEW

**Comment by EnragedWildkin** [comment]
@freevova @tehhi42 Please resolve "Dmytry" (3 times) vs "Dmitry" (5 times). Choose correct spelling.

**Comment by tehhi42** [comment]
@freevova the height of text blocks is different. http://screencast.com/t/KERwPyYmHkRe
I remember that we used to have a script that solved this issue (cc @mir4a )

**Comment by mir4a** [comment]
@freevova @tehhi42 I've created #213  issue for this

**Pull request merged**
