### PR TITLE
SEO Audit

### PR DESCRIPTION
**Pull request by andriyParashchuk**
Setup minimal metrics to achieve for the first version:

0. https://moz.com/blog/how-to-perform-the-worlds-greatest-seo-audit
1. https://blog.hubspot.com/marketing/website-audit
2. https://neilpatel.com

Need to find metrics and find some problems which should be scheduled on this iteration

### CODE REVIEW

**Comment by pftg** [comment]
@andriyParashchuk please update #264 with text how to check that we success

**Comment by pftg** [comment]
also what about:

- Is Your Site Structure Optimized for Search Engines? from https://blog.hubspot.com/marketing/website-audit
- Robots Meta Tags from https://moz.com/blog/how-to-perform-the-worlds-greatest-seo-audit
- (2) Indexability from https://moz.com/blog/how-to-perform-the-worlds-greatest-seo-audit

**Comment by pftg** [comment]
Also please check: http://tools.neilpatel.com/en/analyze/https%3A%2F%2Fwww.jetthoughts.com%2F

**Comment by sweatC** [comment]
Learn more: https://webmasters.googleblog.com/2008/10/importance-of-link-architecture.html
kazam_screenshot_00000
Learn more: https://developers.google.com/web/fundamentals/design-and-ux/responsive/#optimize_text_for_reading
kazam_screenshot_00002

@pftg you can check SEO more properly by using www.google.com/webmasters/ it is only possible for site owner's.

**Comment by andriyParashchuk** [comment]
@sweatC I do not quite understand you. Do you want to change the font size and content?

**Comment by pftg** [comment]
@andriyParashchuk we could think about it later

**Comment by andriyParashchuk** [comment]
@pftg ok. pls check

**Review by obliviusm — APPROVED** [review]
LGTM

**Pull request merged**
