### PR TITLE
Setup Facebook/Twitter/Google Sharing metadata

### PR DESCRIPTION
**Pull request by andriyParashchuk**
Need to provide good looking view when someone shares our site: https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Fjt-test.surge.sh%2F

- [ ] https://developers.facebook.com/docs/sharing/webmasters
- [ ] https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started
- [ ] https://developers.google.com/search/docs/guides/intro-structured-data
- [ ] https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md

To verify we should use: https://developers.facebook.com/tools/debug/sharing/

### CODE REVIEW

**Comment by pftg** [comment]
@andriyParashchuk any updates? what we are going?

**Comment by andriyParashchuk** [comment]
If now good looks, i think this issue can close

**Comment by pftg** [comment]
@andriyParashchuk let's use our long logo: https://drive.google.com/open?id=0B68Li8E9lapnWEZtRUxqTi1SMDQ

also how we are going to test not only facebook but twitter or google meta tags?

**Comment by andriyParashchuk** [comment]
replace logo to 

check in twitter is failed

i think that problem is url (surge.sh)
next actions:
- Fix problem with sharing on twitter from (surge.sh)

**Comment by pftg** [comment]
@andriyParashchuk could post explicit net actions left in order to move this feature

**Pull request closed without merging**
