### PR TITLE
Upgrade packages

### PR DESCRIPTION
**Pull request by pftg**

### CODE REVIEW

**Comment by pftg** [comment]
@andriyParashchuk please verify https://jetthoughts.surge.sh/

**Comment by pftg** [comment]
Found problem will fix it

**Comment by pftg** [comment]
@sweatC please finish this tasks too

**Comment by pftg** [comment]
@sweatC please use CTA to request what need to do next. Please follow https://jtway.co/prepare-the-pull-request-before-asking-to-review-42df362a5c8e

**Comment by sweatC** [comment]
To reviewer: Need to install dependencies and try site functionality. 
Need to verify that all works and new packages don't break something.

**Comment by pftg** [comment]
@sweatC please give a link to staging to test

**Comment by sweatC** [comment]
Sorry, forgot.
Staging: http://jetthoughts-pr-upgrade-packages.surge.sh/

**Comment by ad-sys** [comment]
Looks like nothing is damaged. All good!

**Comment by pftg** [comment]
@sweatC still commit histories is not informative please fix commits

**Comment by pftg** [comment]
also please check that we will have obfuscated and minimized version:

**Comment by sweatC** [comment]
@pftg I have figured out the problem. New version of `jekyll-minifier` only runs when JEKYLL_ENV="production" is set in the environment. So, after deploying to staging with this variable we have minimized version:
image

**Review by andriyParashchuk — APPROVED** [review]
LGTM

**Pull request merged**
