### PR TITLE
Redirect to blog on medium

### PR DESCRIPTION
**Pull request by obliviusm**

### CODE REVIEW

**Comment by obliviusm** [comment]
@pftg it shows all menu items as active locally on home page. is this a bug? 

agile web mobile development - jetthoughts

**Comment by pftg** [comment]
@obliviusm yep, on current version https://cl.ly/181x2M281X2C

**Comment by pftg** [comment]
@obliviusm I think there is hard coded jetthoughts.com there in order to detect current page

**Comment by obliviusm** [comment]
@pftg oh, cool
then it's ready. i've added redirect to one article

**Comment by pftg** [comment]
@obliviusm pls squash commits and remove those css changes

**Comment by obliviusm** [comment]
@pftg now done

**Review by pftg — APPROVED** [review]
LGTM

**Pull request merged**
