### PR TITLE
Install AMP or PWA for performance

### PR DESCRIPTION
**Pull request by andriyParashchuk**
* https://github.com/juusaw/amp-jekyll
* https://github.com/sandoche/Jekyll-webpack-boilerplate

### CODE REVIEW

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-292.surge.sh

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-292.surge.sh

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-292.surge.sh

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-292.surge.sh

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-292.surge.sh

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-292.surge.sh

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-292.surge.sh

**Comment by andriyParashchuk** [comment]
image

**Comment by andriyParashchuk** [comment]
to testing - https://search.google.com/test/amp?id=fnI9_SuOg_H-Pb3G8YKTBQ

**Pull request merged**
