### PR TITLE
#66: Comments count:

### PR DESCRIPTION
**Pull request by mir4a**
– Added disqus identifier for post page.
– Added link maps for migrating from old post links to new for saving comment threads.

### CODE REVIEW

**Comment by mir4a** [comment]
this related to #66

**Comment by mir4a** [comment]
@pftg It used on disqus settings. I left it here for history, if comething went wrong we can run migration on disqus again. Because a lot of work was done yday to get this links right.

**Comment by pftg** [comment]
ok

**Comment by pftg** [comment]
merge if it's ready

**Pull request merged**
