### PR TITLE
Fix content

### PR DESCRIPTION
**Pull request by mir4a**
http://www.jetthoughts.com/tech/2009/10/23/openssl-with-nginx-and-untrusted-ca.html

### CODE REVIEW

**Comment by mir4a** [comment]
http://jetthoughts-github-io-53-fix-c.herokuapp.com/blog/tech/2009/10/23/openssl-with-nginx-and-untrusted-ca.html

**Comment by mir4a** [comment]
@tehhi42 pls verify

**Comment by mir4a** [comment]
compare with http://www.jetthoughts.com/blog/tech/2009/10/23/openssl-with-nginx-and-untrusted-ca.html

**Comment by tehhi42** [comment]
Verified.
http://screencast.com/t/FOlcOTp4R
http://screencast.com/t/yBHuaZ7v1G

**Comment by pftg** [comment]
@tehhi42 do we need PR for this issue?

**Comment by pftg** [comment]
if not, and it's has been deployed already, then close this issue.

**Comment by pftg** [comment]
if needed, then please ask @mir4a to create PR before testing, that you can merge yourselves.

**Pull request merged**
