### PR TITLE
Add sources of used media to repository and update readme with other files

### PR DESCRIPTION
**Pull request by andriyParashchuk**
Google drive - https://drive.google.com/drive/u/1/folders/1NgrTwX6Jj8zjA0zytN3U_bYEYs5gojmE (here is PSD file, fonts, images)
https://www.figma.com/file/wmRuaLaG0wwnOE9kBWfnMn/Jetthoughts-2?node-id=1%3A2 (it is old designe)

### CODE REVIEW

**Comment by andriyParashchuk** [comment]
@obliviusm pls check

**Comment by obliviusm** [comment]
@andriyParashchuk pls also add links to design and psd to README

**Comment by andriyParashchuk** [comment]
Added
@obliviusm check pls

**Review by obliviusm — APPROVED** [review]
LGTM

**Pull request merged**
