### PR TITLE
Image optimization

### PR DESCRIPTION
**Pull request by NazarKY**

### CODE REVIEW

**Comment by NazarKY** [comment]
I have used already used "gulp-imagemin" for <b>images</b> directory instead (as we do it now) using it for <b>source_images</b> directory and pagespeed don't show message to optimize images. But I don't know is it correct to do like so?

**Comment by pftg** [comment]
source images should not be changed, you should transform them and put result in specific directory, which should be used by jekkyl

**Comment by NazarKY** [comment]
One more - task compass creates sprites - and put them into <b>image</b> folder - should I also minimize them or let them be not minimized?

**Comment by pftg** [comment]
@NazarKY for icons i'd like to see `data` protocol, inline images in html

**Pull request closed without merging**
