### PR TITLE
Integration Forestry CMS

### PR DESCRIPTION
**Pull request by andriyParashchuk**
https://forestry.io/

### CODE REVIEW

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-493.surge.sh

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-493.surge.sh

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-493.surge.sh

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-493.surge.sh

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-493.surge.sh

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-493.surge.sh

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-493.surge.sh

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-493.surge.sh

**Comment by andriyParashchuk** [comment]
https://www.loom.com/share/63af4ca2aa4e407286f5a7a1f4c410f8

**Comment by andriyParashchuk** [comment]
Please review

**Pull request merged**
