### PR TITLE
SEO: Add schema .org for AI

### PR DESCRIPTION
**Pull request by andriyParashchuk**
For testing need use - https://search.google.com/structured-data/testing-tool/u/0/

### CODE REVIEW

**Comment by andriyParashchuk** [comment]
@obliviusm pls check

**Comment by obliviusm** [comment]
@andriyParashchuk looks good
please add testing link to `doc/check_performance_and_seo.md`

**Comment by andriyParashchuk** [comment]
@obliviusm Done. Please check again

**Comment by obliviusm** [comment]
Deployed to https://jetthoughts-pr-361.surge.sh

**Review by obliviusm — COMMENTED** [review]
Cool

**Pull request merged**
