### PR TITLE
Change text in uses-cases-slideshow

### PR DESCRIPTION
**Pull request by andriyParashchuk**
Text the same :point_down: 
image

### CODE REVIEW

**Comment by andriyParashchuk** [comment]
staging - jt-pr276.surge.sh/

**Comment by andriyParashchuk** [comment]
@sweatC Pls chek

**Comment by sweatC** [comment]
@andriyParashchuk please add dot at the end of the sentence.
image

**Comment by andriyParashchuk** [comment]
Added

**Review by sweatC — COMMENTED** [review]
LGTM

**Comment by pftg** [comment]
@andriyParashchuk please squash commits and update git commit message

**Comment by andriyParashchuk** [comment]
@pftg  Fixed

**Review by obliviusm — APPROVED** [review]
LGTM

**Pull request merged**
