### PR TITLE
AI: Make 3 first sections

### PR DESCRIPTION
**Pull request by andriyParashchuk**
02_project-desktop- jpg - photos

- [x] Build 3 sections: blue, white and black.
- [x] Add animations

### CODE REVIEW

**Comment by andriyParashchuk** [comment]
Added first sections for desktop (with resolution 1600px)
I will create separate issue for add fonts weight regular
And I create separate issue for elements:


 because i have questions

**Comment by andriyParashchuk** [comment]
Staging - http://jetthoughts-pr344.surge.sh/agentinbox
@obliviusm pls check

**Comment by obliviusm** [comment]
@andriyParashchuk LGTM please rebase on develop to update `Gemfile.lock` and then merge

**Comment by andriyParashchuk** [comment]
@obliviusm pls merge

**Review by obliviusm — COMMENTED** [review]
👍

**Pull request merged**
