### PR TITLE
Share our media files to be accessible by readable public links

### PR DESCRIPTION
**Pull request by sweatC**
We need to put our vector, jpg, png logos, icons, and other media files to public directory in order when we are creating accounts or provide materials to press.

More details could be found on https://trello.com/c/iGzNCyjm/83-create-and-publish-on-site-all-our-media-files-logos-svg-jpg-big-and-small-icon-and-text-separate

- [ ] Gather all files
- [ ] Generate the most popular sizes and formats

### CODE REVIEW

**Comment by sweatC** [comment]
Created JT press folder to store all logos for the press:
https://drive.google.com/drive/folders/1qaB-jEeIuw13beweEVnH_97Ey0emsUQe?usp=sharing
1) If you found some new logos please add it.
2) What sizes and format do we need now?

**Comment by andriyParashchuk** [comment]
@sweatC I see only two files, but we have more social images

**Comment by sweatC** [comment]
@andriyParashchuk pls add this files into a folder.

**Comment by sweatC** [comment]
Added icons with different sizes, old logo, and SVG.

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-411.surge.sh

**Comment by pftg** [comment]
@sweatC often it's requires to have jpg formats. and do we need other sizes too?

**Comment by pftg** [comment]
@sweatC @andriyParashchuk or better to left on github only those files which we are going to require in our metadata, but all other formats host on drive like you have done before?

**Comment by sweatC** [comment]
Idk. I am going to do this kind of task in the first time. @andriyParashchuk pls provide answers.

**Comment by andriyParashchuk** [comment]
@pftg I think it makes sense. But save other formats will be better in https://drive.google.com/drive/u/1/folders/1yVjuYSwctYQmBLw7YHrWmHIPHVq70ox7

**Comment by pftg** [comment]
So what we are expecting on per this PR?

**Comment by pftg** [comment]
@sweatC @andriyParashchuk could you remind what should we do with this PR?

**Pull request closed without merging**
