### PR TITLE
Create a Facebook app

### PR DESCRIPTION
**Pull request by sweatC**
Now we have warning 
image
Need register app on Facebook and add ID in meta data
How Create a Facebook app:
- https://kb.yoast.com/kb/warning-fb-app-id-hasnt-been-included-in-the-meta-tags/

Testing:
https://developers.facebook.com/tools/debug/og/object/

### CODE REVIEW

**Comment by sweatC** [comment]
@obliviusm @andriyParashchuk pls check
Staging: http://jt-pr313.surge.sh/

**Comment by andriyParashchuk** [comment]
Pls change url for staging, because we have same warning

**Comment by sweatC** [comment]
@andriyParashchuk Fixed. Please re-check. Staging: http://jt-pr313.surge.sh/
image

**Comment by andriyParashchuk** [comment]
if scroll down, we has
but I do not know if this is a warning

**Comment by andriyParashchuk** [comment]
@sweatC It is ok?

**Comment by sweatC** [comment]
@andriyParashchuk it is info message. We didn't publish our app to the public, it is ok.

**Review by andriyParashchuk — COMMENTED** [review]
LGTM
@obliviusm pls check

**Comment by obliviusm** [comment]
Let's close this issue
As info message says provided app id is not used.
Original message has info type not warning. So no big need to fix it

**Pull request closed without merging**
