### PR TITLE
Check Social Sharing Metadata

### PR DESCRIPTION
**Pull request by andriyParashchuk**
Need check and fix meta data on:
- facebook - https://developers.facebook.com/tools/debug/og/object/
- twitter - https://cards-dev.twitter.com/validator

Need change meta description

https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started
https://moz.com/blog/meta-data-templates-123

### CODE REVIEW

**Comment by andriyParashchuk** [comment]
staging - http://jt-pr308.surge.sh/

**Comment by andriyParashchuk** [comment]
Now we have warning 
image
This warning will be fix in #313

**Comment by andriyParashchuk** [comment]
@obliviusm @sweatC pls check

**Comment by sweatC** [comment]
@andriyParashchuk for Facebook it works fine, but for twitter I didn't get exactly the same card as you have in your screenshot.
image
image
image

**Comment by andriyParashchuk** [comment]
@sweatC 
You do not test twitter card.
Because Twitter blocks surge.sh, so I tested on GitHub Pages (not staging)

**Comment by sweatC** [comment]
@andriyParashchuk looks nice
image

**Review by sweatC — APPROVED** [review]
LGTM

**Pull request merged**
