### PR TITLE
Minify HTML

### PR DESCRIPTION
**Pull request by NazarKY**
https://developers.google.com/speed/docs/insights/MinifyResources

### CODE REVIEW

**Comment by NazarKY** [comment]
Want to try another gulp plugin [minify-html](https://github.com/jonathanepollack/gulp-minify-html)

**Comment by NazarKY** [comment]
common size of HTML  is reduced by 29%

**Comment by NazarKY** [comment]
Test results for [WORK page](http://www.webpagetest.org/video/compare.php?tests=150120_GT_EQF,150120_V2_EQG)
Test results for [INDEX page](http://www.webpagetest.org/video/compare.php?tests=150120_NP_ERJ,150120_ZW_ERK)

According to this results minifying of html gives us at least 0.4s quicker  loading

**Comment by pftg** [comment]
> Minifying http://www.jetthoughts.com/ could save 693B (14% reduction) after compression. See optimized content

@NazarKY please take a look

**Comment by NazarKY** [comment]
Is it possible to run gulp task automatically after jekyll build?
do we have some jekyll-build task. Is it <i>gulp default</i>?

If yes- than it's not working - can somebody check - if it is only my issue - all it's not working in others too?

**Pull request merged**
