### PR TITLE
AI: Make next 3 sections

### PR DESCRIPTION
**Pull request by andriyParashchuk**
02_project-desktop- jpg - photo2s

### CODE REVIEW

**Comment by obliviusm** [comment]
Deployed to https://jetthoughts-pr-346.surge.sh

**Comment by andriyParashchuk** [comment]
AI page - https://jetthoughts-pr-346.surge.sh/agentinbox

**Comment by andriyParashchuk** [comment]
@obliviusm pls check

**Comment by obliviusm** [comment]
let's add a dot
ruby on rails react mobile web development

**Review by obliviusm — COMMENTED** [review]
LGTM please fix comment above in next PR

**Pull request merged**
