### PR TITLE
Get Contact Form Request on Email

### PR DESCRIPTION
**Pull request by obliviusm**
I need to be able to see message from contact form.

fix google form sending (currently in code)
or : https://formspree.io/

### CODE REVIEW

**Comment by obliviusm** [comment]
@andriyParashchuk pls review.
 staging http://jt-305.surge.sh/
let's do it this way. you can test staging and send form. and then i will post received data from google doc here

**Comment by andriyParashchuk** [comment]
@obliviusm sent the message

**Comment by obliviusm** [comment]
image

@andriyParashchuk

**Review by andriyParashchuk — APPROVED** [review]
LGTM

**Pull request merged**
