### PR TITLE
Configure www/non-www page redirects

### PR DESCRIPTION
**Pull request by SviridovSV**
image

### CODE REVIEW

**Comment by SviridovSV** [comment]
staging: http://jt-pr328.surge.sh

**Comment by pftg** [comment]
@SviridovSV, please

1. compare https://www.jetthoughts.com and https://jetthoughts.com
2. Find infographics how browser get content from user place URL and hit enter and till browser render content. Should cover HTTP and server high overview how it’s working. Let’s assume this is Nginx server.
3. Question: what response status code we got on https://jetthoughts.com
3. Question: is it possible to see your changes if the server returns 404
4. Question: why we got 404?

**Review by pftg — CHANGES_REQUESTED** [review]
This will not help us

**Comment by SviridovSV** [comment]
@pftg - About infographics http://igoro.com/archive/what-really-happens-when-you-navigate-to-a-url
- response of https://jetthoughts.com : SSL: certificate subject name '*.github.com' does not match target host name 'jetthoughts.com'
- if server returns 404 my changes will not be available
- we got 404, perhaps, due to not correct or absent redirection on server side

**Comment by pftg** [comment]
@SviridovSV please post here summary is it related should we close or find another solution?

**Comment by SviridovSV** [comment]
@pftg  As soon as we found out that problem was with DNS, I think, my fixes are unnecessary and this issue can be closed

**Pull request closed without merging**
