### PR TITLE
[Content] Add tools to AI page

### PR DESCRIPTION
**Pull request by andriyParashchuk**
image

### CODE REVIEW

**Comment by andriyParashchuk** [comment]
@pftg Can you give links on RETS and MLS tools?

**Comment by pftg** [comment]
MLS https://en.m.wikipedia.org/wiki/Multiple_listing_service - найти где то надо если нет - то забей
REST - замени на  RESO и вот их иконка https://www.reso.org/

**Comment by andriyParashchuk** [comment]
@pftg Thanks

**Comment by andriyParashchuk** [comment]
Staging - http://jetthoughts-377.surge.sh/agentinbox
image

**Comment by andriyParashchuk** [comment]
@pftg Please check

**Comment by pftg** [comment]
@andriyParashchuk

**Comment by andriyParashchuk** [comment]
@pftg Changed. Please check again.

**Review by pftg — APPROVED** [review]
LGTM

**Comment by pftg** [comment]
@andriyParashchuk please squash and merge

**Pull request merged**
