### PR TITLE
Save all logos on the web page

### PR DESCRIPTION
**Pull request by andriyParashchuk**
https://trello.com/c/8z7V2DKw/440-%D1%81%D0%BE%D0%B1%D1%80%D0%B0%D1%82%D1%8C-%D0%B2%D1%81%D0%B5-%D0%BD%D0%B0%D1%88%D0%B8-%D0%BB%D0%BE%D0%B3%D0%BE%D1%82%D0%B8%D0%BF%D1%8B-%D1%81-%D1%80%D0%B0%D0%B7%D0%BD%D1%8B%D0%BC%D0%B8-%D1%80%D0%B0%D0%B7%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D1%8F%D0%BC%D0%B8-%D0%B8-%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D0%B0%D0%BC%D0%B8-%D0%BD%D0%B0-%D0%BE%D0%B4%D0%BD%D0%BE%D0%B9-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B5

### CODE REVIEW

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-467.surge.sh

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-467.surge.sh

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-467.surge.sh

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-467.surge.sh

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-467.surge.sh

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-467.surge.sh

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-467.surge.sh

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-467.surge.sh

**Comment by andriyParashchuk** [comment]
please review

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-467.surge.sh

**Comment by andriyParashchuk** [comment]
@SviridovSV, please review

**Comment by andriyParashchuk** [comment]
for testing https://www.loom.com/share/885482a7766043898c3b012de8c3d284

**Review by SviridovSV — APPROVED** [review]

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-467.surge.sh

**Comment by SviridovSV** [comment]
@andriyParashchuk @dgorodnichy Please review the fix

**Review by dgorodnichy — APPROVED** [review]
LGTM

**Comment by andriyParashchuk** [comment]
LGTM

**Pull request merged**
