### PR TITLE
Fix the spacing 

### PR DESCRIPTION
**Pull request by andriyParashchuk**
https://monosnap.com/file/rFTo7RizHG9CdC13MrDgkJ2kZzD1ib
https://monosnap.com/file/42nuOwQzKz5LvkEB0tSOuqO0ubf4NV
https://monosnap.com/file/p1SILw3mhkJKqNar5HdDM3W2N1E1Cu
https://monosnap.com/file/YmqSw5SIl5PgH8huWxCCc4SqlgRqom

### CODE REVIEW

**Comment by andriyParashchuk** [comment]
In this PR also was fixed #385

**Comment by andriyParashchuk** [comment]
Staging - http://jetthoughts-pr384.surge.sh/agentinbox

@pftg @ad-sys Please check

**Comment by ad-sys** [comment]
Wow, it looks awesome, much more readable now! The only flaw I found is: https://monosnap.com/file/x19v25RfsRFHDPLIP2WOPx8893hGSz

**Comment by andriyParashchuk** [comment]
@ad-sys Fixed. Please check again

**Comment by andriyParashchuk** [comment]
@ad-sys Oh, one moment. Found bug

**Comment by ad-sys** [comment]
OK)

**Comment by andriyParashchuk** [comment]
@ad-sys Done.

**Comment by ad-sys** [comment]
tested and merged

**Pull request merged**
