### PR TITLE
Setup new blog posts on Home page

### PR DESCRIPTION
**Pull request by SviridovSV**
Need to change blog posts to new one, maybe we should change posts only for the first section to:

- [x] https://jtway.co/the-4-steps-to-bringing-life-to-a-struggling-project-37a53bf9c7dc
- [x] https://jtway.co/how-to-get-remote-teams-to-high-perform-b9b29d698feb
- [x] https://jtway.co/inexpensive-is-not-cheap-choosing-software-development-company-for-your-project-da97b7d9b3c0

*NOTE:* In order to change them we need to have good looking title which will not break layout

For section in the middle we could add several new one: 

- [x] https://jtway.co/inexpensive-is-not-cheap-choosing-software-development-company-for-your-project-da97b7d9b3c0
- [x] https://jtway.co/the-simplest-way-to-automate-delivery-of-your-react-native-application-f37f2c71eb1d
- [x] https://jtway.co/how-to-setup-a-project-that-can-host-up-to-1000-users-for-free-ab59ad3edaf1

### CODE REVIEW

**Comment by SviridovSV** [comment]
staging: http://jt-pr339.surge.sh/

**Comment by SviridovSV** [comment]
@pftg Please, verify view for the first section: do we need to change titles on better looking?

**Comment by pftg** [comment]
Please replace text everywhere from "Inexp.." to "Inexpensive is Not Cheap."

**Comment by pftg** [comment]
Please add posts to the middle sections:

1. https://jtway.co/how-we-hire-developers-at-jetthoughts-d71e8b88e62c
2. https://jtway.co/a-typical-day-at-jetthoughts-460b84eeb9c6

**Comment by pftg** [comment]
@SviridovSV please check my comments

**Review by pftg — COMMENTED** [review]
LGTM

**Pull request merged**
