### PR TITLE
Need to redirect all request from `/blog/*` to `jtway.co`

### PR DESCRIPTION
**Pull request by sweatC**
This bug fixed here: https://github.com/jetthoughts/jetthoughts.github.io/pull/290
https://cl.ly/3Y3u321t2J0j/Image%202018-04-12%20at%2020.32.56.public.png

### CODE REVIEW

**Comment by andriyParashchuk** [comment]
@sweatC  Pls change branch to develop

**Review by pftg — COMMENTED** [review]
change base branch

**Comment by sweatC** [comment]
This bug fixed here: #290

**Pull request closed without merging**
