### PR TITLE
Animation artifacts on IPad 

### PR DESCRIPTION
**Pull request by SviridovSV**
Need disable animation on IPad and IPad Pro

### CODE REVIEW

**Comment by SviridovSV** [comment]
staging: http://320.surge.sh/

**Comment by SviridovSV** [comment]
@pftg please add me to https://app.ghostinspector.com

**Comment by pftg** [comment]
@SviridovSV please get credentials from @andriyParashchuk in slack

**Comment by andriyParashchuk** [comment]
@SviridovSV 
dev@jetthoughts.com
jetthoughtsisthebest

**Comment by andriyParashchuk** [comment]
Animation on IPad https://www.useloom.com/share/c87bc7f74bfc47c5b83fd088c1519ef3

**Comment by pftg** [comment]
@SviridovSV have you updated server for verification?

**Comment by pftg** [comment]
Could we have a more general solution not only for iPad but for other tablets? or this will be hard?

My first solution was to detect that we have @2 and 1300 / 2 in order to calculate that this is the small screen. Is it possible to find this?

**Comment by pftg** [comment]
tested on ipad, and it looks good

**Pull request merged**
