### PR TITLE
Change style of headings for the blog 

### PR DESCRIPTION
**Pull request by ultroned**

### CODE REVIEW

**Comment by ultroned** [comment]
@pftg and @tehhi42 ,

here's how new changes are look (my suggestion):
1) H3: bold + margin-top: 2em;
2) H1: bold + font-size: 2.1em;
3) a href class="author" has the same color as hover <li>

it s time for active job

**Comment by tehhi42** [comment]
Looks nice. @pftg Your opinion?

**Comment by pftg** [comment]
:shipit: - mean :+1:

**Comment by ultroned** [comment]
@pftg and @tehhi42, 

new changes are ready.

**Comment by pftg** [comment]
Still old styles on production, @mir4a how to apply new styles to old posts?

**Comment by mir4a** [comment]
@loogle18 have you tried `gulp` tasks? There is a task for compass and stylesheets minification. @pftg suggest add similar styles for h2 as well.

**Comment by pftg** [comment]
@mir4a :+1:

**Comment by pftg** [comment]
@loogle18 please add new issue for h2 fix

**Pull request merged**
