### PR TITLE
Enable sitemaps if there is no

### PR DESCRIPTION
**Pull request by mir4a**
https://help.github.com/articles/sitemaps-for-github-pages

### CODE REVIEW

**Comment by mir4a** [comment]
The application will be deployed to: http://jetthoughts-github-io-111-site.herokuapp.com
Monitor the job status at: http://instapusher.com/projects/jetthoughts-jetthoughts-github-io/jobs/1129

**Comment by mir4a** [comment]
@tehhi42 pls verify

**Comment by tehhi42** [comment]
Verified.
http://screencast.com/t/CkIH9XegQkv

**Comment by tehhi42** [comment]
@pftg may I merge this PR?

**Comment by pftg** [comment]
yes

**Pull request merged**
