### PR TITLE
Align titles in posts

### PR DESCRIPTION
**Pull request by andriyParashchuk**
Align titles veritcally 
image

Medium label should be on the same height

### CODE REVIEW

**Comment by andriyParashchuk** [comment]
In this issue will be fix #365

**Comment by obliviusm** [comment]
Deployed to https://jetthoughts-pr-359.surge.sh

**Comment by andriyParashchuk** [comment]
@obliviusm pls check

**Review by obliviusm — COMMENTED** [review]
LGTM

**Pull request merged**
