### PR TITLE
Improve AI Case

### PR DESCRIPTION
**Pull request by andriyParashchuk**
image

image
https://twitter.com/elliotkoolik

image
https://mandrillapp.com/

Remove section
image

### CODE REVIEW

**Comment by andriyParashchuk** [comment]
Staging - http://jetthoughts-pr379.surge.sh/agentinbox

**Comment by andriyParashchuk** [comment]
@ad-sys Please check.

**Comment by pftg** [comment]
@andriyParashchuk please rebase and redeploy

**Comment by ad-sys** [comment]
Looks good, can go further

**Review by ad-sys — APPROVED** [review]
Good!

**Pull request merged**
