### PR TITLE
[Content] Replace content on agentinbox page

### PR DESCRIPTION
**Pull request by andriyParashchuk**
https://docs.google.com/document/d/1Qleg9wJrKQgcAn7QMr5Xm1QToZMtR2u0LAmXXC1HUF8/edit?usp=sharing

### CODE REVIEW

**Comment by andriyParashchuk** [comment]
Staging - http://jetthoughts-375.surge.sh/agentinbox

**Comment by andriyParashchuk** [comment]
@pftg Please review

**Comment by pftg** [comment]
@andriyParashchuk please update content again https://docs.google.com/document/d/1RrH28EjSW4b-BuqiGsax0JXtGJ5JoS5NPlavXqoEdEA/edit but make sure that we should have 2-3 sentences per paragraph

**Comment by andriyParashchuk** [comment]
@pftg I don't sure, for what section this content. We should add a new section with paragraphs in agent inbox page?

**Comment by pftg** [comment]
@andriyParashchuk sorry I missed doc. Here it is correct:https://docs.google.com/document/d/1Qleg9wJrKQgcAn7QMr5Xm1QToZMtR2u0LAmXXC1HUF8/edit?usp=sharing

**Comment by andriyParashchuk** [comment]
@pftg Please check

**Comment by andriyParashchuk** [comment]
image

**Comment by andriyParashchuk** [comment]
@pftg Peplaced `Ukraine - Miami` to `Ukraine - USA`. Please check.

**Review by pftg — APPROVED** [review]
Content looks good!

**Comment by pftg** [comment]
We need to review UI updates after this and decide how to make it looks better

**Pull request merged**
