### PR TITLE
Changes to the website

### PR DESCRIPTION
**Pull request by andriyParashchuk**
- [x] Add: Full visibility and transparency of job done
 image

- [x] Clutch and Glassdoor change - no icons - just text 
Glassdoor
https://www.glassdoor.com/Overview/Working-at-JetThoughts-EI_IE456589.11,22.htm
Clutch  
https://clutch.co/profile/jetthoughts

- [ ]  Change button location
image
- [ ]  Add under we make apps  :
There is a stressless way to deliver products, and we want to share it with as many people as possible.
- [x] We build applications for mobile, from highly technical internal tools to robust *customer facing* interfaces.
change to:   customer-facing 

- [x]  Using Ruby on Rails we can bring secure products to market quickly. Change to: 
 Using Ruby on Rails, we can instantly bring reliable products onto the market.

- [x]  React Native allows us to build mobile apps faster while maintaining world-class mobile user experience. Change to: 
 React Native allows us to build mobile apps faster while maintaining world-class mobile user experience.
- [x] Add comma before React.js in this sentence: 
 We bring elegant solutions into your web projects using Ruby on Rails, Vue.js, React.js, and more. 
- [ ] Add Address under JetThoughts LLC at the footer:  
340 S Lemon Ave #7503 
Walnut, CA 91789, USA

#Dev page
- [x] Developers who won’t let you down. We offer fully managed dedicated tech team, consisting of full-stack Ruby on Rails, Vue.js , React and React Native software engineers.

CHANGE TO: 
Developers who won’t let you down. We offer a fully managed dedicated tech team consisting of full-stack Ruby on Rails, Vue.js, React, and React Native software engineers.

- [x] We offer a 2-week trial period to see how it goes, no financial risks to hire a team and test everything.

Add a comma at the end ' , and test everything.'

### CODE REVIEW

**Comment by andriyParashchuk** [comment]
Create separate issues:
- #442 
- #441

**Comment by andriyParashchuk** [comment]
@ad-sys please review

**Comment by andriyParashchuk** [comment]
staging - http://439-site-improvements.surge.sh/

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-439.surge.sh

**Pull request merged**
