### PR TITLE
Remove unnecessary files and folders from compilation

### PR DESCRIPTION
**Pull request by NazarKY**

### CODE REVIEW

**Comment by NazarKY** [comment]
@pftg: pls take a look I have removed all unnecessary files from compilation.
PS: There still are a lot of .js files and maybe not all of them are using - should I investigate them also?

**Comment by NazarKY** [comment]
By this [link](http://www.aymerick.com/2014/07/22/jekyll-github-pages-bower-bootstrap.html) (in section Setup bower) I found that we can exclude bower_components  from jekyll build and ignore them

**Comment by NazarKY** [comment]
@pftg: pls review

**Comment by pftg** [comment]
@NazarKY please delete branch

**Pull request merged**
