### PR TITLE
Improve UI part of AI

### PR DESCRIPTION
**Pull request by andriyParashchuk**
Текст сильно в стовбчик на цих участках (Lenovo x240 ноут та планш Samsung t807t)
image
image

image

### CODE REVIEW

**Comment by ad-sys** [comment]
image

**Comment by ad-sys** [comment]
image

**Comment by ad-sys** [comment]
https://www.google.com/search?q=jeffrey+dahmer&rlz=1C5CHFA_enUS686US686&oq=jeffrey+da&aqs=chrome.0.69i59j69i57j0l4.1924j0j7&sourceid=chrome&ie=UTF-8

**Comment by andriyParashchuk** [comment]
Staging - http://jetthoughts-pr380.surge.sh/agentinbox

**Comment by andriyParashchuk** [comment]
@ad-sys I created the separate issue #381 for change name

**Comment by andriyParashchuk** [comment]
@pftg @ad-sys Please check

**Comment by ad-sys** [comment]
Looks good to me, the only thing is that the frame bottom borders are different for Elliot Koolik and Tylers quotes, 
image
the other thing is that even though we have separated the text now those rows are  hard to read because text goes to a new line with no logic in it.

**Comment by andriyParashchuk** [comment]
@ad-sys I created a separate issue about quote height #383

**Comment by andriyParashchuk** [comment]
@ad-sys Can I merge this pull-request?

**Review by pftg — APPROVED** [review]
https://www.useloom.com/share/332575e3181742cdbd6b3a6003737791

## Some improvments will be great to have:

- [ ]

**Review by ad-sys — COMMENTED** [review]
all good, could be merged

**Comment by andriyParashchuk** [comment]
@pftg It's different section, but we can change font size to same. I Created issue about it #385

**Pull request merged**
