### PR TITLE
Carousel doesn't work properly

### PR DESCRIPTION
**Pull request by andriyParashchuk**
Carousel doesn't work properly.
Come on, he switches from AI to Farius then again on AI and breaks.
https://www.useloom.com/share/0b9be2ca95934218b3e7c20f214b61eb

### CODE REVIEW

**Comment by pftg** [comment]
@sweatC please verify

**Comment by sweatC** [comment]
@pftg @andriyParashchuk It doesn't work properly
https://www.useloom.com/share/9a82ad4f27324145bbe9fa4b50868ee5

**Comment by andriyParashchuk** [comment]
@sweatC  pls check - http://jt-pr277.surge.sh/

**Review by sweatC — COMMENTED** [review]
LGTM

**Review by pftg — CHANGES_REQUESTED** [review]
@andriyParashchuk please update git commit message: https://cl.ly/341E1F3A3L3v/Image%202018-04-28%20at%2016.50.09.public.png

**Comment by andriyParashchuk** [comment]
@pftg  Fixed

**Comment by obliviusm** [comment]
@andriyParashchuk i think you can make it better. pls check https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message check questions in this article
i think you should say in title what you've done (but without tech details, we have code for that)
and in description you say what problem your change have solved and how it did it. actually it doesn't clear how speed change fixes double-clicking just from code

**Comment by andriyParashchuk** [comment]
@obliviusm Done

**Review by obliviusm — APPROVED** [review]

**Pull request merged**
