### PR TITLE
Updated metadata in order to display more data on Google Search Results

### PR DESCRIPTION
**Pull request by andriyParashchuk**
There are structures per each stuff: https://developers.google.com/search/reference/overview

### CODE REVIEW

**Comment by andriyParashchuk** [comment]
Was fixed `json-ld` script. 
@pftg @ad-sys Please review

**Comment by andriyParashchuk** [comment]
@pftg Updated commit message

**Comment by ad-sys** [comment]
Google needs some time to get these changes applied, checked it but getting no results yet

**Comment by pftg** [comment]
@andriyParashchuk has not been fixed yet:  let's schedule fix again

**Pull request merged**
