### PR TITLE
Add categories page for blog posts

### PR DESCRIPTION
**Pull request by tmwh**
Use the same layout for blog list page.

### CODE REVIEW

**Comment by tmwh** [comment]
Changed path to config.rb in generator_scss plugin, so now compass will compile css assets when jekyll recompiles pages instead of displaying error.
Added categories pages. Moved posts collection rendering into _includes folder. Changed links on blog posts, they now starting with /blog prefix.

**Comment by miry** [comment]
@tmwh pls rebase against master and deploy to heroku.(without instapusher).

**Comment by tmwh** [comment]
@miry done
http://jetthoughts-37-categories.herokuapp.com/blog/

**Comment by miry** [comment]
@tmwh pls rebase again.
@annkuptsova  pls verify

**Comment by tmwh** [comment]
@miry done.
Also updated here:
http://jetthoughts-37-categories.herokuapp.com/blog/

**Comment by miry** [comment]
@annkuptsova pls verify

**Comment by tehhi42** [comment]
Verified.

**Pull request closed without merging**
