### PR TITLE
Performance: Meaningful render should be less than 1 sec

### PR DESCRIPTION
**Pull request by andriyParashchuk**
References: https://developers.google.com/web/tools/lighthouse/audits/first-meaningful-paint

### CODE REVIEW

**Comment by andriyParashchuk** [comment]
staging - http://jt-pr256.surge.sh/

**Comment by pftg** [comment]
@andriyParashchuk please use call to action format if you want someone to do something. Do you want someone to verify this changes?

**Comment by andriyParashchuk** [comment]
@sweatC Pls check

**Comment by pftg** [comment]
@andriyParashchuk please update messages for commits (no need to squash if they are different) and ready for merge

**Comment by andriyParashchuk** [comment]
Yes, I understand my mistake
It's not squash, I made everything one commit

**Comment by pftg** [comment]
there is no mistake, just need to clean up it ;)

**Comment by andriyParashchuk** [comment]
- staging - http://jt-pr256.surge.sh/

- Disconnected custom fonts, because they too long rendered
- Issue will be created in which will need to connect custom fonts

**Comment by andriyParashchuk** [comment]
@sweatC Pls check

**Review by pftg — COMMENTED** [review]
LGTM

**Pull request merged**
