### PR TITLE
Fix Ui bugs

### PR DESCRIPTION
**Pull request by sweatC**
- Fix arrow in main screen

- Fix description in footer

### CODE REVIEW

**Comment by sweatC** [comment]
@obliviusm @andriyParashchuk pls check
Staging: http://jt-pr312.surge.sh/
screenshot_2018-05-15-21-11-25
screenshot_2018-05-15-21-44-08

**Comment by andriyParashchuk** [comment]
- Arrow drag on reload 
https://www.useloom.com/share/6e4f69ce16a6495a866d55efc19e29f7
- footer destroy in desktop

**Comment by sweatC** [comment]
@andriyParashchuk pls send design for desktop I only swapped contacts with description.
About arrow I don't know exactly.

**Comment by sweatC** [comment]
@andriyParashchuk pls verify http://jt-pr312.surge.sh/

**Comment by andriyParashchuk** [comment]
different spacing

**Comment by obliviusm** [comment]
@sweatC to simplify review you can post screenshots for: design, was, now. both mobile and desktop

**Comment by sweatC** [comment]
@obliviusm accepted. @andriyParashchuk pls re-check.
Design:
image
App:
image

**Review by andriyParashchuk — COMMENTED** [review]
LGTM

**Comment by andriyParashchuk** [comment]
@obliviusm pls check on iphone

**Review by obliviusm — APPROVED** [review]
LGTM
iphone 5s looks good

**Pull request merged**
