### PR TITLE
Setup Assets Including and Compilation

### PR DESCRIPTION
**Pull request by mir4a**
## Fro Production
- [x] use all js at the bottom
- [x] compile all js files in one file
- [x] compile all css in one file
- [ ] setup digesting
- [ ] setup multi-hosts for assets uri's

### CODE REVIEW

**Comment by mir4a** [comment]
The application will be deployed to: http://jetthoughts-github-io-106-setu.herokuapp.com
Monitor the job status at: http://instapusher.com/projects/jetthoughts-jetthoughts-github-io/jobs/1391

**Comment by mir4a** [comment]
The application will be deployed to: http://jetthoughts-github-io-106-setu.herokuapp.com
Monitor the job status at: http://instapusher.com/projects/jetthoughts-jetthoughts-github-io/jobs/1410

**Comment by mir4a** [comment]
@tehhi42 pls verify and @pftg pls make code review

**Comment by pftg** [comment]
@mir4a PR please

**Comment by mir4a** [comment]
@pftg it was rebased already

**Comment by tehhi42** [comment]
@mir4a Fonts are loading very slowly. http://screencast.com/t/5YNTQeqM

**Comment by mir4a** [comment]
The application will be deployed to: http://jetthoughts-github-io-106-setu.herokuapp.com
Monitor the job status at: http://instapusher.com/projects/jetthoughts-jetthoughts-github-io/jobs/1420

**Comment by mir4a** [comment]
@tehhi42 pls verify

**Comment by pftg** [comment]
@tehhi42 I'll merge this PR after review, please just comment what you have found

**Comment by tehhi42** [comment]
@pftg Fonts are loading slow in Chrome (Win). Tried opening the link in an incognito mode - works fine. 
No problems in Firefox and IE.

**Comment by pftg** [comment]
@mir4a what is the best to use pure css: https://fonts.googleapis.com/css?family=Lato:300,400,700,900,700italic:latin or js version?

**Comment by mir4a** [comment]
@pftg I choose js because it gives more control on font loading. It applied css classes so I can choose when show system font and when custom.

**Comment by mir4a** [comment]
@pftg I think we can close this PR it is redundant and outdated, check #125

**Pull request closed without merging**
