### PR TITLE
Add ghostinspector tests per different resolutions and devices

### PR DESCRIPTION
**Pull request by obliviusm**
We support several resolutions and need to compare screenshots for all of them.

And need to test on different Browsers

Screns: 1920x1080, 1600x900, 1366x768, 1024x768, 1024x640, 768x1024, 360x640, 640x360

### CODE REVIEW

**Comment by sweatC** [comment]
@obliviusm 
image

**Comment by sweatC** [comment]
@pftg please add me to https://app.ghostinspector.com for collaboration.

**Comment by obliviusm** [comment]
@pftg @andriyParashchuk @sweatC pls check
staging http://jt-297.surge.sh/?height=768px&stop_animation=true
fixed tests: 
stop slider: https://app.ghostinspector.com/tests/5aec67c388762859e5a6230a
red thing: https://app.ghostinspector.com/tests/5aec649588762859e5a60318
new test 16x10: https://app.ghostinspector.com/tests/5af1621f4f8a53106dbf9dbc

**Comment by obliviusm** [comment]
@pftg i checked https://api.jquery.com/jquery.fx.off/
but it doesn't help with our carousel. 
can we leave it as it is here?

**Comment by sweatC** [comment]
@obliviusm pls check
image
image

**Comment by obliviusm** [comment]
@andriyParashchuk pls verify and merge if it is ok

**Review by andriyParashchuk — APPROVED** [review]
LGTM

**Comment by pftg** [comment]
Please delete branch after merge

**Comment by andriyParashchuk** [comment]
Deleted

**Pull request merged**
