### PR TITLE
Fix Google console

### PR DESCRIPTION
**Pull request by andriyParashchuk**
image
image

### CODE REVIEW

**Comment by andriyParashchuk** [comment]
I fixed language tag, but for "HTML Improvements" need select on https://www.jetthoughts.com/, not https://jetthoughts.com/ 


Because we have added our site using "www"
https://support.google.com/webmasters/answer/96568?authuser=1&hl=en#2

**Comment by andriyParashchuk** [comment]
@obliviusm @sweatC pls check
staging - http://jt-pr310.surge.sh/

**Comment by sweatC** [comment]
@andriyParashchuk what I found:
image
image

**Comment by obliviusm** [comment]
@sweatC i think lang attribute should fix that

**Review by obliviusm — APPROVED** [review]
LGTM
@sweatC pls merge when you sure that it's good

**Comment by andriyParashchuk** [comment]
@obliviusm of rights. 
@sweatC you look at the production without the attribute lang

**Review by sweatC — APPROVED** [review]

**Pull request merged**
