### PR TITLE
Add Google Strucutred Data

### PR DESCRIPTION
**Pull request by andriyParashchuk**
https://developers.google.com/search/docs/guides/intro-structured-data?visit_id=1-636583792682452694-854283534&hl=en&rd=1

### CODE REVIEW

**Comment by andriyParashchuk** [comment]
staging - http://jt-pr259.surge.sh/
you can check structured this - https://search.google.com/structured-data/testing-tool/u/0/

**Comment by andriyParashchuk** [comment]
@pftg @obliviusm @sweatC  pls check

**Comment by pftg** [comment]
is it ok?

**Comment by pftg** [comment]
do we need this: https://cl.ly/3e372T270g05/Image%202018-05-11%20at%2014.52.54.public.png

**Comment by pftg** [comment]
https://cl.ly/3V3v2l2r2m0U/Image%202018-05-11%20at%2014.53.35.public.png

**Comment by pftg** [comment]
https://cl.ly/2L1R0O3p2u38/Image%202018-05-11%20at%2014.53.58.public.png

**Comment by pftg** [comment]
@andriyParashchuk please check my comments above

**Comment by andriyParashchuk** [comment]
1. Sure, it is for input tag
2. No, it is for contact page
3. it is link to blog
4. accepted
5. there is type BlogPosting, but for her need author, date Published,image...
6. accepted

**Comment by pftg** [comment]
> there is type BlogPosting, but for her need author, date Published,image...

you could grab this from blog post iteself

**Comment by andriyParashchuk** [comment]
@pftg @obliviusm @sweatC 
staging - http://jt-pr259.surge.sh/
pls check structured this - https://search.google.com/structured-data/testing-tool/u/0/

**Comment by sweatC** [comment]
@andriyParashchuk pls check
image
For each BlogPosting row
image

**Comment by sweatC** [comment]
I read Slack and found that you and @pftg have discussed that `jetthoughts.com` must be WebPage not Organization. Do I right?
image

**Comment by sweatC** [comment]
Also, @pftg you can use https://www.google.com/webmasters/tools/googlebot-fetch to test it properly. This tool available only for the owner.

**Comment by sweatC** [comment]
@andriyParashchuk do we have sitemap fo images? 
Because all image URLs must be crawlable and indexable. 
Otherwise, Google will not be able to display them on the search results page.
See: https://support.google.com/webmasters/answer/178636
I think you need to create type for each service.
image
Instead of using name in Web Page.
image

**Comment by pftg** [comment]
@sweatC I added you on https://github.com/jetthoughts/jetthoughts.github.io/pull/259#issuecomment-388880606

**Comment by pftg** [comment]
@andriyParashchuk please check comments from @sweatC

**Comment by andriyParashchuk** [comment]
@sweatC 
1. It is ok. We do not have date modified
2. It is organization
3. We use jekyll-sitemap plugin.
4. It is not services, just title in slider

**Comment by andriyParashchuk** [comment]
@pftg pls check

**Comment by andriyParashchuk** [comment]
@obliviusm pls check

**Comment by andriyParashchuk** [comment]
Updated images for posts meta data and updated staging http://jt-pr259.surge.sh/
pls check

**Comment by sweatC** [comment]
@andriyParashchuk thanks for your feedback. Approved.

**Review by sweatC — APPROVED** [review]
LGTM

**Pull request merged**
