### PR TITLE
Make meta details for AI page more relevant to the page content

### PR DESCRIPTION
**Pull request by andriyParashchuk**
https://cl.ly/bb4d073455db

Make sure cover: https://github.com/jetthoughts/jetthoughts.github.io/pull/396#discussion_r278406588

### CODE REVIEW

**Comment by andriyParashchuk** [comment]
@pftg @sweatC @ad-sys Please review

**Comment by ad-sys** [comment]
I think we can delete Agent Inbox from the title, it will give more space to other things since we already have agent inbox in link

**Comment by pftg** [comment]
Deployed to https://jetthoughts-pr-398.surge.sh

**Comment by andriyParashchuk** [comment]
@ad-sys Removed `Agent Inbox` from the title

**Comment by ad-sys** [comment]
Perfect

**Pull request merged**
