### PR TITLE
Improve preview of the site

### PR DESCRIPTION
**Pull request by andriyParashchuk**
Will be great to improve our unfurl preview in messengers to be more aggressive and fix on other messengers

- [x] Discord does not show any information at all: 
- [x] Change format to be more like on Mailgun: 
- [ ] Build list tools where we are going to test unfurl preview: Twitter, Facebook, LinkedIn, reddit posts/comments, Discord, Slack, Telegram, LinkedIn Messenger, Facebook Messenger, Skype, Medium Comments, YHackernews and other

### CODE REVIEW

**Comment by pftg** [comment]
Also will be great to review in complex with #390

**Comment by andriyParashchuk** [comment]
@pftg Let's merge this PR for testing preview because we can't check preview on staging

**Comment by pftg** [comment]
@andriyParashchuk merged

**Comment by ad-sys** [comment]
Just checked https://monosnap.com/file/z2lxFhc3o3hjvRqg2fKPlNZe6K5FqI

**Pull request merged**
