### PR TITLE
Added new blog post with description and images

### PR DESCRIPTION
**Pull request by mir4a**

### CODE REVIEW

**Comment by pftg** [comment]
@mir4a would you merge today?

**Comment by mir4a** [comment]
@pftg, I want @tehhi42 to check [description](https://github.com/jetthoughts/jetthoughts.github.io/pull/210/files#diff-8a9d17c1cde15177314b852cc1475024R24) section and then merge

**Comment by tehhi42** [comment]
@mir4a checked, committed a few changes, looks good.

**Comment by pftg** [comment]
@mir4a pls merge

**Pull request merged**
